### ISSUE TITLE
[feat] Sort /watch Feed By Accept-Language Header

### ISSUE THREAD

**Issue by phroggster** [crowbartools/firebot-website#2]
It would be **really** cool if /watch.tsx sorted the feed according to the http Accept-Language header sent to it. No fancy sorting desired beyond that, just English-speaking streamers at the top of "my" list, followed by a mix of Spanish and French, then German, with any others below that, assuming: "en-US, en;q=0.9, fr;q=0.7, es;q=0.7, de:q=0.6, *;q=0.5".

**Comment by ebiggz** [comment]
Hey @phroggster,

I've just added support for some sort and filter query params to the `/watch` page. Here are the deets:

### Sorting Param
- `sortBy`
    - Options: `language`, `stream_uptime`, and `viewers`
    - Each option can be suffixed with `:desc` or `:asc` (no suffix defaults to `asc`)
    - Define multiple with commas
    - "language" sort uses accept-language header by default
    - Default: `language:desc,stream_uptime:asc`
### Filter Params
- `language`
  - Options: [ISO 639-1 two-letter language code](https://www.loc.gov/standards/iso639-2/php/code_list.php) or "other"
  - Define multiple with commas
  - If defined, used for language sort instead of accept-language header
- `category`
  - Options: Twitch category id or name
     - If name, it will query twitch api to find closest match
     - Define multiple with commas
- `mature`
  - Options: "true" or "false"
- `search`
  -  Text matched against channel name, stream title, and tags
  
  
So now, by default, the /watch page will sort based on the Accept-Language header 👍🏻

**Comment by ebiggz** [comment]
Closing as released. Thanks for the great suggestion!
